const CATALOG = [
    {
        id:'001',
        name:'Пицца "Четыре сыра"',
        img:'images/pizza_four_cheese.jpg',
        weight:'500г',
        price:399,
    },
    {
        id:'002',
        name:'Пицца с морепродуктами',
        img:'images/pizza_sea_food.jpg',
        weight:'500г',
        price:399,
    },
    {
        id:'003',
        name:'Пицца "Маргарита"',
        img:'images/pizza_margarita.jpg',
        weight:'500г',
        price:399,
    },
    {
        id:'004',
        name:'Пицца "Пепперони"',
        img:'images/pizza_pepperoni.jpg',
        weight:'500г',
        price:299,
    },
    {
        id:'005',
        name:'Пицца "Гавайская"',
        img:'images/pizza_hawaiian.jpg',
        weight:'500г',
        price:399,
    },
    {
        id:'006',
        name:'Пицца "Диабло"',
        img:'images/pizza_diablo.jpg',
        weight:'600г',
        price:499,
    },
    {
        id:'007',
        name:'Пицца "Римская"',
        img:'images/pizza_romanian.jpg',
        weight:'700г',
        price:499,
    },
    {
        id:'008',
        name:'Пицца "Маринара"',
        img:'images/pizza_marinara.jpg',
        weight:'500г',
        price:399,
    },
    {
        id:'009',
        name:'Пицца "Капричиоза"',
        img:'images/pizza_capriciossa.jpg',
        weight:'500г',
        price:399,
    },
    {
        id:'010',
        name:'Пицца "Четыре сезона"',
        img:'images/pizza_4_seasons.jpg',
        weight:'450г',
        price:499,
    },
    {
        id:'011',
        name:'Пицца "Баварская"',
        img:'images/pizza_bavarian.jpg',
        weight:'500г',
        price:299,
    },
    {
        id:'012',
        name:'Пицца "Мексиканская"',
        img:'images/pizza_mexican.jpg',
        weight:'500г',
        price:399,
    },
];
